FDA_USER: "user@nyu.edu"
FDA_PASS: "password"
CSV_DSPACE_LOOKUP_TABLE_URL: "https://raw.githubusercontent.com/OpenGeoMetadata/edu.nyu/master/misc/handle-dspace-lookup.csv"
FDA_REST_ENDPOINT: "https://archive.nyu.edu/rest"
